### PR TITLE
pretext commit to open discussion

### PR DESCRIPTION
**Pull request by d-k-c**
This is just a `git add -u` commit to open the discussion about termdebug and how we could move forward with this. I see two options:

1. Keep this is a separate script. I don't know where it would live and I don't really want to maintain a vim script considering my script development is more trials and errors to see what works than real development.
2. Integration with upstream termdebug. To support our use case, we only need two things to be integrated in termdebug: being able to launch a GDB Server (or similar) and overriding the default program pty with another command (telnet, kermit, you name it).

I'm not really familiar with Vim development, who has ownership of termdebug and who is in charge of defining the set of features it should have or not, but if we could go with option 2 then imho it would be the best.

Thank you for your help and your review upstream :)

### CODE REVIEW

**Comment by ubaldot** [comment]
> 1. Keep this is a separate script. I don't know where it would live and I don't really want to maintain a vim script considering my script development is more trials and errors to see what works than real development.

I understand. My idea is to make a simple plugin out of this script so I will be in charge to maintain it and matching with the evolution on the upstram termdebug. Users will only have to config some variables. However, at the moment this script is part of my .vimrc, so I am actually maintaining it.

> 2. Integration with upstream termdebug. To support our use case, we only need two things to be integrated in termdebug: being able to launch a GDB Server (or similar) and overriding the default program pty with another command (telnet, kermit, you name it).
> 

I think we may need more: what about a serial monitor window? :) 
And if we start brainstorming I am sure we will pull out additional requirements. 
I think a plugin that extends termdebug is the cleaner solution. I will make it after I will have prepared a good termdebug. ;-) 

> I'm not really familiar with Vim development, who has ownership of termdebug and who is in charge of defining the set of features it should have or not, but if we could go with option 2 then imho it would be the best.
> 
> Thank you for your help and your review upstream :)

**Comment by d-k-c** [comment]
>  I will make it after I will have prepared a good termdebug. ;-)

Could you expand on that? :)

**Comment by ubaldot** [comment]
I am currently refactoring it by making it more robust, readable and maintainable. Vim9 allow us to do that. I just sent a PR, you could take a look at it. Next, I plan to add a sanity check and a more configurable way of mapping - now we have only three fixed mapping: K, + and -. I think we can extend it.

Anyway, my final goal is also to split it in multiple files because the plugin is fairly large and having it in just one file may fire back in the long run. But I think I am running out of time for this tasks, so perhaps I will skip such a breakdown, or I will do it in veeery small steps.

Btw, I don't know if you have seen it but there are a number of use-cases that actually don't apply only to embedded systems so the option of hiding the debugged program window is accepted! Then, I discovered that also Bram wanted it.  If you want and have time feel free to send a PR! :)

**Comment by ubaldot** [comment]
@d-k-c Hello!
Just to inform you that I finally made a plugin as mentioned a while ago. It is based on Termdebug but with micro-controllers target. 
Here it is: https://github.com/ubaldot/vim-microdebugger 

It is still in early phase, but I would really appreciate if you could try it and gimme some feedback. :)

**Comment by d-k-c** [comment]
That's awesome thanks for keeping me posted, I'll give it a try as soon as I can

**Pull request closed without merging**
